config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index, :show, :edit]
  root 'home#index'


  get '/edit_profile', to: 'users#edit', as: :edit_profile
  post '/search', to: 'home#search'
  post '/redo', to: 'home#redo'
  get '/sign_out', to: 'sessions#destroy', as: :sign_out
  get '/sign_in', to: 'sessions#new', as: :sign_in
  post '/sign_in', to: 'sessions#create', as: :login

end

app/views/layouts/_content.html.erb
<section class='row'>
  <%= yield %>
</section>

app/views/layouts/_footer.html.erb
<footer class='row'>
  <p>Made by <a href="http://rpy.herokuapp.com">Rebecca Paz</a>.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class='navbar navbar-default' role='navigation'>

    <% if signed_in? %>
      <div class="navbar-header">
        <a class='navbar-brand'>Welcome, <%= current_user.name %></a>
      </div>
    <% end %>

    <div class='collapse navbar-collapse' id='navbar-collapse-3'>
      <ul class='nav navbar-nav'>
        <li>
          <%= link_to "Home", root_path %>
        </li>

        <% if signed_in? %>

          <li>
            <%= link_to "Sign out", sign_out_path %>
          </li>

          <li>
            <%= link_to "Edit profile", edit_profile_path %>
          </li>

        <% else %>

          <li>
            <%= link_to "Register", new_user_path %>
          </li>
          <li>
            <%= link_to "Sign in", sign_in_path %>
          </li>

        <% end %>

      </ul>

      <% if signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class='dropdown'>

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Meal History <span class='caret'></span>
            </a>

            <ul class="dropdown-menu" role="menu">
              <% current_user.meal_history.each do |meal| %>
                <li><a href="#"><%= meal %></a></li>
              <% end %>
            </ul>

          </li>
        </ul>
      <% end %>
    </div>

  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComboBreaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= render 'layouts/header' %>

  <% if flash[:error] %>
  <div class='alert alert-danger' role='alert'>
    <%= "#{flash[:error]} Please try again!" %>
  </div>
  <% end %>

  <%= render 'layouts/content' %>

  <%= render 'layouts/footer' %>
</div>

</body>
</html>